### ISSUE TITLE
Mac OS test error: Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE

### ISSUE THREAD

**Issue by OxygenLiu** [qd-cae/qd-cae-python#48]
Hello there, thank you very much for qd-cae library! 

I am trying to install it on my Mac Book Pro, but fail to pass tests.  

+ Mac OS: High Sierra 10.13.6 
+ g++ version: Homebrew GCC 8.3.0 
+ python: 3.7.2  
+ FEMZIP: N/A 

Compilation is good by using `sudo python setup.py install`, however, it fails when `sudo python setup.py test`,

```
Traceback (most recent call last):
  File "/Users/xjl/projects/qd-cae-python/qd/cae/dyna.py", line 4, in <module>
    from .dyna_cpp import *
ImportError: dlopen(/Users/xjl/projects/qd-cae-python/qd/cae/dyna_cpp.cpython-37m-darwin.so, 2): Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE
  Referenced from: /Users/xjl/projects/qd-cae-python/qd/cae/dyna_cpp.cpython-37m-darwin.so
  Expected in: flat namespace
 in /Users/xjl/projects/qd-cae-python/qd/cae/dyna_cpp.cpython-37m-darwin.so
```
Any hint of this issue? Looking forward to your response!

Oxygen

**Comment by lasso-codie** [comment]
Hi Liu,
that looks like a classic linking issue. I assume you have more than one compiler installed. It seems that pip links towards one stdc++ library, but at runtime takes another one (from possibly the other compiler). I can't tell any more specific since it depends on environment variables etc, but from your information it seems that the issue is just present at runtime. Are you using system python or anaconda python? How does your env variables `LD_LIBRARY_PATH` and `PATH` look like. Note I'm not very familiar with MacOS though.

**Comment by OxygenLiu** [comment]
Thank you for the feedback! After cleaning up `$PATH`, and recompile qd-cae, there is some progress now.  

```
~/projects/qd-cae-python> python setup.py test
FEMZIP library not found. Compiling without FEMZIP.
running test
running egg_info
writing qd.egg-info/PKG-INFO
writing dependency_links to qd.egg-info/dependency_links.txt
writing requirements to qd.egg-info/requires.txt
writing top-level names to qd.egg-info/top_level.txt
reading manifest file 'qd.egg-info/SOURCES.txt'
writing manifest file 'qd.egg-info/SOURCES.txt'
running build_ext
copying build/lib.macosx-10.13-x86_64-3.7/qd/cae/dyna_cpp.cpython-37m-darwin.so -> qd/cae
test_binout (test_dyna.TestDynaModule)
Testing qd.cae.dyna.Binout ... ok
test_dyna_d3plot (test_dyna.TestDynaModule)
Testing qd.cae.dyna.D3plot ... ERROR
test_keyfile (test_dyna.TestDynaModule) ... ok
test_numerics_sampling (test_dyna.TestDynaModule)
Testing qd.numerics ... /usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: RuntimeWarning: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216, got 192
  return f(*args, **kwds)
/usr/local/Cellar/python/3.7.2_2/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/_bootstrap.py:219: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  return f(*args, **kwds)
/Users/xjl/projects/qd-cae-python/qd/numerics/sampling.py:52: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.
  vars_bounds = np.vstack( variables[label] for label in variable_labels )
ok
test_qd_cae_beta (test_dyna.TestDynaModule)
Testing qd.cae.beta ... ok
test_raw_d3plot (test_dyna.TestDynaModule) ... ok

======================================================================
ERROR: test_dyna_d3plot (test_dyna.TestDynaModule)
Testing qd.cae.dyna.D3plot
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/xjl/projects/qd-cae-python/test/test_dyna.py", line 131, in test_dyna_d3plot
    Element.shell, 4).shape, (4696, 4))
ValueError: cannot create a pybind11::array_t from a nullptr

----------------------------------------------------------------------
Ran 6 tests in 2.370s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=6 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=6 errors=1 failures=0>
```

The error message seems irrelevant, I can import and query d3plot file smoothly.

**Comment by lasso-codie** [comment]
Yeah at least it works. I just hope I didn't screw up somewhere. There should never be such an error since the shouldn't be any `nullptr` at all ... Tests run fine on my machine but it is running OpenSuse.
By the way thumbs up :+1:  for running tests. You're my hero of the day. Let me know if you recognize any runtime issues with other files too.
